/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

/**
 *
 * @author yasmi
 */
public class formCRUDadmin extends javax.swing.JFrame {

    /**
     * Creates new form CRUDadmin
     */
    public formCRUDadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cbSkala = new javax.swing.JComboBox<>();
        cbNamamatkul = new javax.swing.JComboBox<>();
        txtNamatugas = new javax.swing.JTextField();
        txtTenggat = new javax.swing.JTextField();
        txtCariIDtugas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCaritugas = new javax.swing.JButton();
        btnBuattugas = new javax.swing.JButton();
        btnHapustugas = new javax.swing.JButton();
        btnEdittugas = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnKeluarCRUD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(100, 90, 65));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 249, 234));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 290, 180));

        cbSkala.setBackground(new java.awt.Color(100, 90, 65));
        cbSkala.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        cbSkala.setForeground(new java.awt.Color(255, 255, 255));
        cbSkala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tinggi", "Sedang", "Rendah" }));
        cbSkala.setBorder(null);
        cbSkala.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbSkala.setMinimumSize(new java.awt.Dimension(418, 29));
        cbSkala.setPreferredSize(new java.awt.Dimension(418, 29));
        cbSkala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSkalaActionPerformed(evt);
            }
        });
        getContentPane().add(cbSkala, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 320, 300, 40));

        cbNamamatkul.setBackground(new java.awt.Color(100, 90, 65));
        cbNamamatkul.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        cbNamamatkul.setForeground(new java.awt.Color(255, 255, 255));
        cbNamamatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemrograman Berbasis Objek", "Desain Manajemen Jaringan Komputer", "Desain Manajemen Proses Bisnis", "Riset Operasi", "Interaksi Manusia dan Komputer", "Desain Basis Data", "Dasar-Dasar Pengembangan Perangkat Lunak" }));
        cbNamamatkul.setBorder(null);
        cbNamamatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamamatkulActionPerformed(evt);
            }
        });
        getContentPane().add(cbNamamatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 290, 40));

        txtNamatugas.setBackground(new java.awt.Color(100, 90, 65));
        txtNamatugas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtNamatugas.setForeground(new java.awt.Color(255, 249, 234));
        txtNamatugas.setBorder(null);
        getContentPane().add(txtNamatugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 270, 30));

        txtTenggat.setBackground(new java.awt.Color(100, 90, 65));
        txtTenggat.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTenggat.setForeground(new java.awt.Color(255, 249, 234));
        txtTenggat.setBorder(null);
        getContentPane().add(txtTenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 270, 30));

        txtCariIDtugas.setBackground(new java.awt.Color(100, 90, 65));
        txtCariIDtugas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtCariIDtugas.setForeground(new java.awt.Color(255, 249, 234));
        txtCariIDtugas.setBorder(null);
        getContentPane().add(txtCariIDtugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 440, 20));

        jTable1.setBackground(new java.awt.Color(228, 198, 122));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 950, 180));

        btnCaritugas.setBackground(new java.awt.Color(228, 198, 122));
        btnCaritugas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCaritugas.setForeground(new java.awt.Color(100, 90, 65));
        btnCaritugas.setBorder(null);
        btnCaritugas.setBorderPainted(false);
        btnCaritugas.setContentAreaFilled(false);
        getContentPane().add(btnCaritugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 140, 40));

        btnBuattugas.setBackground(new java.awt.Color(228, 198, 122));
        btnBuattugas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnBuattugas.setForeground(new java.awt.Color(100, 90, 65));
        btnBuattugas.setBorder(null);
        btnBuattugas.setBorderPainted(false);
        btnBuattugas.setContentAreaFilled(false);
        getContentPane().add(btnBuattugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 130, 130, 40));

        btnHapustugas.setBackground(new java.awt.Color(228, 198, 122));
        btnHapustugas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnHapustugas.setForeground(new java.awt.Color(100, 90, 65));
        btnHapustugas.setBorder(null);
        btnHapustugas.setBorderPainted(false);
        btnHapustugas.setContentAreaFilled(false);
        getContentPane().add(btnHapustugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 130, 30));

        btnEdittugas.setBackground(new java.awt.Color(228, 198, 122));
        btnEdittugas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnEdittugas.setForeground(new java.awt.Color(100, 90, 65));
        btnEdittugas.setBorder(null);
        btnEdittugas.setBorderPainted(false);
        btnEdittugas.setContentAreaFilled(false);
        getContentPane().add(btnEdittugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 260, 130, 30));

        btnRefresh.setBackground(new java.awt.Color(228, 198, 122));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(100, 90, 65));
        btnRefresh.setBorder(null);
        btnRefresh.setBorderPainted(false);
        btnRefresh.setContentAreaFilled(false);
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 130, 30));

        btnKeluarCRUD.setBackground(new java.awt.Color(228, 198, 122));
        btnKeluarCRUD.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnKeluarCRUD.setForeground(new java.awt.Color(100, 90, 65));
        btnKeluarCRUD.setBorder(null);
        btnKeluarCRUD.setBorderPainted(false);
        btnKeluarCRUD.setContentAreaFilled(false);
        getContentPane().add(btnKeluarCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/LOGIN (7).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSkalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSkalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSkalaActionPerformed

    private void cbNamamatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamamatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNamamatkulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCRUDadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCRUDadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCRUDadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCRUDadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCRUDadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuattugas;
    private javax.swing.JButton btnCaritugas;
    private javax.swing.JButton btnEdittugas;
    private javax.swing.JButton btnHapustugas;
    private javax.swing.JButton btnKeluarCRUD;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbNamamatkul;
    private javax.swing.JComboBox<String> cbSkala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtCariIDtugas;
    private javax.swing.JTextField txtNamatugas;
    private javax.swing.JTextField txtTenggat;
    // End of variables declaration//GEN-END:variables
}
