/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

/**
 *
 * @author yasmi
 */
public class formRegistrasi extends javax.swing.JFrame {

    /**
     * Creates new form Registrasi
     */
    public formRegistrasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRegisnama = new javax.swing.JTextField();
        txtRegisemail = new javax.swing.JTextField();
        passRegis = new javax.swing.JPasswordField();
        passRegiskonfir = new javax.swing.JPasswordField();
        btnXregis = new javax.swing.JButton();
        btnRegis = new javax.swing.JButton();
        btnLogindiregis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRegisnama.setBackground(new java.awt.Color(187, 147, 48));
        txtRegisnama.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtRegisnama.setBorder(null);
        getContentPane().add(txtRegisnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 500, 40));

        txtRegisemail.setBackground(new java.awt.Color(187, 147, 48));
        txtRegisemail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtRegisemail.setBorder(null);
        getContentPane().add(txtRegisemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 500, 40));

        passRegis.setBackground(new java.awt.Color(187, 147, 48));
        passRegis.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        passRegis.setBorder(null);
        getContentPane().add(passRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 500, 50));

        passRegiskonfir.setBackground(new java.awt.Color(187, 147, 48));
        passRegiskonfir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        passRegiskonfir.setBorder(null);
        getContentPane().add(passRegiskonfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 500, 50));

        btnXregis.setBackground(new java.awt.Color(255, 249, 234));
        btnXregis.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnXregis.setForeground(new java.awt.Color(100, 90, 65));
        btnXregis.setText("X");
        btnXregis.setBorder(null);
        btnXregis.setBorderPainted(false);
        btnXregis.setContentAreaFilled(false);
        getContentPane().add(btnXregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, -1, -1));

        btnRegis.setBackground(new java.awt.Color(228, 198, 122));
        btnRegis.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegis.setBorder(null);
        btnRegis.setBorderPainted(false);
        btnRegis.setContentAreaFilled(false);
        getContentPane().add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 230, 60));

        btnLogindiregis.setBackground(new java.awt.Color(255, 249, 234));
        btnLogindiregis.setBorder(null);
        btnLogindiregis.setBorderPainted(false);
        btnLogindiregis.setContentAreaFilled(false);
        getContentPane().add(btnLogindiregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 110, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegistrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogindiregis;
    private javax.swing.JButton btnRegis;
    private javax.swing.JButton btnXregis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passRegis;
    private javax.swing.JPasswordField passRegiskonfir;
    private javax.swing.JTextField txtRegisemail;
    private javax.swing.JTextField txtRegisnama;
    // End of variables declaration//GEN-END:variables
}
